compiler:
    solc:
        optimize: true
        runs: 200
        version: 0.8.12
#        remappings:
#          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
#dependencies:
#    - OpenZeppelin/openzeppelin-contracts@4.6.0
